# Generated by Django 2.2.1 on 2019-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('publisher', models.CharField(max_length=250, verbose_name='Publisher')),
                ('isbn', models.CharField(max_length=250, null=True, verbose_name='ISBN')),
                ('notes', models.TextField(max_length=2500, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100, verbose_name='Breed')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Birth Date')),
                ('color', models.CharField(choices=[('br', 'Brown'), ('bl', 'Black'), ('wh', 'White'), ('go', 'Gold')], max_length=2, verbose_name='Color')),
                ('unique_features', models.TextField(max_length=100, verbose_name='Unique Features')),
            ],
        ),
    ]
