# Generated by Django 2.2.1 on 2019-05-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollections', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
