# Generated by Django 2.2.1 on 2019-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollections', '0002_delete_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Notes'),
        ),
    ]
